name: Web Testing Automation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup Java 11
      - name: Setup JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11

      # 3. Cache Gradle dependencies
      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # 4. Grant permission to gradlew
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 5. Install Chrome
      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      # 6. Setup ChromeDriver
      - name: Setup ChromeDriver
        uses: nanasess/setup-chromedriver@v2

      # 7. Upload JUnit Test Report
      - name: Upload JUnit Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-test-report
          path: build/reports/tests/test

      # 8. Upload Cucumber HTML Report
      - name: Upload Cucumber HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-html-report
          path: |
            build/reports/cucumber/
            build/cucumber-reports/
