name: UI Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Install Chrome & ChromeDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable chromium-chromedriver
        google-chrome --version
        chromedriver --version

    - name: Grant execute permission for Gradlew
      run: chmod +x gradlew

    - name: Run Tests
      run: ./gradlew test

    - name: Show build folder structure
      run: |
        echo "===== BUILD FOLDER STRUCTURE ====="
        find build -type f

    - name: Upload JUnit Test Report
      uses: actions/upload-artifact@v4
      with:
        name: junit-report
        path: build/reports/tests/test

    - name: Upload Cucumber HTML Report
      uses: actions/upload-artifact@v4
      with:
        name: cucumber-report
        path: build/cucumber-reports
